packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  # dev tools
  eslint: ^9.19.0
  prettier: ^3.4.2
  tailwindcss: ^3.4.15
  typescript: ^5.7.3

  # Misc
  zod: ^3.24.1

  # Tanstack & tRPC
  "@tanstack/react-query": ^5.59.15
  "@trpc/client": ^11.0.0-rc.477
  "@trpc/react-query": ^11.0.0-rc.477
  "@trpc/server": ^11.0.0-rc.477

  # Next.js
  next: ^15.2.3

  "dotenv-cli": ^8.0.0

catalogs:
  react19:
    react: 19.0.0
    react-dom: 19.0.0
    "@types/react": ^19.0.0
    "@types/react-dom": ^19.0.0
